In [1]:
import numpy as np

# CREATING ARRAY

In [54]:
array = np.array([1,2,3,4,5,6,7,8])

In [55]:
print(array)

[1 2 3 4 5 6 7 8]


# CREATING MATRIX

In [15]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [16]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# TRANSPOSING MATRIX

In [20]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# SQUARE OF NUMBERS

In [25]:
#underroot of 25
square = np.sqrt(25)

In [26]:
square

5.0

In [144]:
square1 = np.square(5)

In [145]:
square1

25

# ARRANGE NUMBERS

In [28]:
arrange = np.arange(1,100)

In [29]:
arrange

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# LINESPACE

In [30]:
linespace = np.linspace(1,10,2)

In [31]:
linespace

array([ 1., 10.])

# RESHAPING

In [57]:
#we do reshping of arrays to shape it into matrix form
array.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

# ZEROS

In [49]:
zeros = np.zeros([4,4])

In [42]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# ONES

In [37]:
ones = np.ones([4,5])

In [38]:
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# IDENTITY MATRIX

In [46]:
ident = np.eye(5,4)

In [47]:
ident

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

# UNIQUE

In [59]:
variable = np.array([1,2,3,4,3,2,1,4,"john","love","got","love","dare"])

In [60]:
variable

array(['1', '2', '3', '4', '3', '2', '1', '4', 'john', 'love', 'got',
       'love', 'dare'], dtype='<U11')

In [61]:
np.unique(variable)

array(['1', '2', '3', '4', 'dare', 'got', 'john', 'love'], dtype='<U11')

# mathematical operations of 2 arrays

In [62]:
array2 = np.array([4,5,6,7,2,7,4,8])

In [66]:
array3 = array+array2

In [67]:
array3

array([ 5,  7,  9, 11,  7, 13, 11, 16])

In [68]:
array4 = array*array2

In [69]:
array4

array([ 4, 10, 18, 28, 10, 42, 28, 64])

In [70]:
array5 = array-array2

In [71]:
array5

array([-3, -3, -3, -3,  3, -1,  3,  0])

In [72]:
array6 = array/array2

In [73]:
array6

array([0.25      , 0.4       , 0.5       , 0.57142857, 2.5       ,
       0.85714286, 1.75      , 1.        ])

# RANDOM NUMBER 

In [99]:
random = np.random.randn(4,3)

In [100]:
random

array([[ 0.59370083,  0.60530481, -1.33041212],
       [-0.98346689,  0.27773487, -0.320655  ],
       [-0.38203357,  0.11154035, -1.64257972],
       [ 1.67407817,  0.7958533 , -0.32483813]])

In [135]:
random1 = np.random.rand(4,3)

In [136]:
random1

array([[0.7637347 , 0.53695018, 0.76529261],
       [0.72442411, 0.94938854, 0.86412191],
       [0.44250435, 0.58200207, 0.45114452],
       [0.43388307, 0.75907833, 0.75648887]])

# RANDOM NUMBERS GENERATION AND SORTING

In [121]:
random_number = np.random.randint(10,20, size=10)

In [127]:
random_number

array([12, 17, 13, 13, 19, 18, 11, 13, 17, 10])

In [128]:
np.sort(random_number)

array([10, 11, 12, 13, 13, 13, 17, 17, 18, 19])

In [129]:
np.max(random)

1.6740781665973599

In [130]:
np.min(random)

-1.64257972187533

In [137]:
random>random1

array([[False,  True, False],
       [False, False, False],
       [False, False, False],
       [ True,  True, False]])

In [141]:
print(random[random>1])

[1.67407817]
